/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
        
        import {
  useGLTF,
} from '@react-three/drei'
import { useRef } from 'react'
        
        
        export default function Model(props: any) {
          const group = useRef()
          const { nodes, materials }: any = useGLTF("/tree-spruce.gltf")
          return (
            <group ref={group} {...props} dispose={null}>
        <mesh castShadow geometry={nodes['tree-spruce'].geometry} material={materials.color_main} />

            </group>
          )
        }

useGLTF.preload('/tree-spruce.gltf')